base_images:
  os:
    cluster: https://api.ci.openshift.org
    name: centos
    namespace: openshift
    tag: '7'
binary_build_commands: make install
canonical_go_repository: github.com/openshift/demo-component
images:
- from: os
  to: some-demo-image
- from: os
  to: other-demo-image
resources:
  '*':
    limits:
      cpu: '2'
      memory: 6Gi
    requests:
      cpu: 100m
      memory: 200Mi
test_base_image:
  cluster: https://api.ci.openshift.org
  name: release
  namespace: openshift
  tag: golang-1.10
tests:
- as: unit
  commands: make test
  from: src
- as: lint
  commands: make lint
  from: src
- as: integration
  commands: make integration
  from: bin
