kind: List
apiVersion: v1
items:
- apiVersion: batch/v1beta1
  kind: CronJob
  metadata:
    name: "image-mirror-tekton-v0.3-quay"
    namespace: ci
    labels:
      app: "image-mirror-tekton-v0.3-quay"
  spec:
    schedule: "0 * * * *"
    concurrencyPolicy: Forbid
    successfulJobsHistoryLimit: 1
    failedJobsHistoryLimit: 2
    jobTemplate:
      spec:
        template:
          metadata:
            name: "image-mirror-tekton-v0.3-quay"
            labels:
              app: "image-mirror-tekton-v0.3-quay"
          spec:
            restartPolicy: OnFailure
            volumes:
              - name: push
                secret:
                  secretName: registry-push-credentials-quay.io-openshift-pipeline
              - name: config
                configMap:
                  name: image-mirror
            containers:
              - name: "mirror"
                image: "openshift/origin-cli:v4.1"
                terminationMessagePolicy: FallbackToLogsOnError
                volumeMounts:
                  - name: push
                    mountPath: /home/mirror/.docker/config.json
                    subPath: config.json
                  - name: config
                    mountPath: /etc/imagemirror
                env:
                  - name: HOME
                    value: /home/mirror
                command:
                  - oc
                args:
                  - image
                  - mirror
                  - -f=/etc/imagemirror/mapping_tekton_v0_3_quay
                  - --skip-multiple-scopes # quay chokes when requesting multiple
- apiVersion: batch/v1beta1
  kind: CronJob
  metadata:
    name: "image-mirror-tekton-v0.4-quay"
    namespace: ci
    labels:
      app: "image-mirror-tekton-v0.4-quay"
  spec:
    schedule: "0 * * * *"
    concurrencyPolicy: Forbid
    successfulJobsHistoryLimit: 1
    failedJobsHistoryLimit: 2
    jobTemplate:
      spec:
        template:
          metadata:
            name: "image-mirror-tekton-v0.4-quay"
            labels:
              app: "image-mirror-tekton-v0.4-quay"
          spec:
            restartPolicy: OnFailure
            volumes:
              - name: push
                secret:
                  secretName: registry-push-credentials-quay.io-openshift-pipeline
              - name: config
                configMap:
                  name: image-mirror
            containers:
              - name: "mirror"
                image: "openshift/origin-cli:v4.1"
                terminationMessagePolicy: FallbackToLogsOnError
                volumeMounts:
                  - name: push
                    mountPath: /home/mirror/.docker/config.json
                    subPath: config.json
                  - name: config
                    mountPath: /etc/imagemirror
                env:
                  - name: HOME
                    value: /home/mirror
                command:
                  - oc
                args:
                  - image
                  - mirror
                  - -f=/etc/imagemirror/mapping_tekton_v0_4_quay
                  - --skip-multiple-scopes # quay chokes when requesting multiple
